# Appveyor config file for SuperCollider
# Author: Brian Heim
# Created on 2017-12-31
# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}' # incremented with each build

# shallow_clone doesn't clone, repository is not git so can't get submodules
clone_depth: 10

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2013

environment:
    CMAKE_CONFIGURATION: Release
    ASIO_URL: "http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip"
    ASIO_ZIP: asiosdk2.3.zip

    matrix:
        - QT_DIR: "C:/Qt/5.5/msvc2013"
          CMAKE_GENERATOR: "Visual Studio 12 2013"
          FFTW_URL: ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll32.zip
          ARCH: "x86"

        - QT_DIR: "C:/Qt/5.5/msvc2013_64"
          CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
          FFTW_URL: ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll64.zip
          ARCH: "x64"

install:
- ps: echo "Install phase start"

- ps: $env:PROGFILES = if ($env:ARCH -eq "x64") { 'Program Files' } else { 'Program Files (x86)' }

- ps: echo "Get submodules"
- git submodule update --init

# Install libsndfile, FFTW, and ASIO SDK. Note that DirectX SDK, Windows SDK are already installed.
- ps: echo "Install 3rd-party tools"
- ps: New-Item -ItemType directory -Name 3rdparty | Out-Null
- ps: cd 3rdparty

# libsndfile using hosted repository. Couldn't find a way to get the installer to work silently.
- ps: echo "Install libsndfile"
- ps: New-Item -ItemType directory -Name libsndfile | Out-Null
- ps: cd libsndfile
- ps: echo $env:LIBSNDFILE
- cmd: git clone https://github.com/brianlheim/libsndfile-windows-%ARCH% libsndfile
- ps: $env:MEGANERD_DIR = "C:/$env:PROGFILES/Mega-Nerd"
- ps: New-Item -ItemType directory -Path "$env:MEGANERD_DIR" | Out-Null
- ps: Move-Item libsndfile "$env:MEGANERD_DIR/libsndfile"
- ps: cd ..
- ps: echo "Done installing libsndfile"

# FFTW3, including lib prep
- ps: echo "Install fftw"
- ps: New-Item -ItemType directory -Name fftw | Out-Null
- ps: cd fftw
- ps: Invoke-WebRequest $env:FFTW_URL -OutFile fftw.zip
- ps: 7z x fftw.zip -y
- cmd: "\"C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/lib\" /machine:%ARCH% /def:libfftw3f-3.def"
- ps: cd ..
- ps: Get-ChildItem .
- ps: Move-Item fftw "C:/$env:PROGFILES/fftw"
- ps: echo "Done installing fftw"

# ASIO SDK
- ps: echo "Install asio_sdk"
- ps: New-Item -ItemType directory -Name asio_sdk | Out-Null
- ps: cd asio_sdk
- appveyor DownloadFile %ASIO_URL%
- ps: 7z x $env:ASIO_ZIP -y
- ps: Get-ChildItem .
- ps: Move-Item ASIOSDK2.3 "$env:APPVEYOR_BUILD_FOLDER\external_libraries\asiosdk"
- ps: cd ..
- ps: echo "Done installing asio_sdk"

- ps: cd ..
- ps: echo "Done installing 3rd-party tools"

- ps: echo "Install phase end"

before_build:
- set PATH=%QT_DIR%\bin;%PATH%
- mkdir build
- cd build

build_script:
- cmake -G "%CMAKE_GENERATOR%" -D CMAKE_PREFIX_PATH=%QT_DIR% ..
- cmake --build . --target install --config %CMAKE_CONFIGURATION%

notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/0f811b8a74efd99f4a4e
      on_build_status_changed: true
      on_build_failure: true
      on_build_success: false
